import { fontIceland, fontInter } from "@/lib/fonts";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren, ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CosmWasm Tracing UI",
  description: "Generated by create next app",
};

type RootLayoutProps = PropsWithChildren & {
  span: ReactNode;
};

export default function RootLayout({ children, span }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={fontInter.className}>
        <Providers>
          <>
            {children}
            {span}
          </>
        </Providers>
      </body>
    </html>
  );
}
